### ISSUE TITLE
Installation freezes during Building Kaldi tools

### ISSUE THREAD

**Issue by ghost** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020#10]
Attaching the screenshot for reference. Please help me to resolve this. Thanks
![Screenshot from 2021-05-06 21-15-56](https://user-images.githubusercontent.com/38154800/117353604-9c054400-aeb0-11eb-8403-ab7fb0a49bb3.png)

**Comment by charishnaidu** [comment]
![Screenshot from 2021-05-06 21-15-56](https://user-images.githubusercontent.com/38154800/117353841-ef779200-aeb0-11eb-86dc-e953744a3424.png)

**Comment by ghost** [comment]
shorten_x.c:464:6: warning: implicit declaration of function ‘swab’ [-Wimplicit-function-declaration]
  464 |      swab(writebuf, writefub, sizeout * nchanout * nitem);
      |      ^~~~
openfst-1.6.7.tar.gz                                         3%[===>                                                                                                                                  ]  37.99K   119KB/s               sph2pipe.c: In function ‘getUserOpts’:
sph2pipe.c:191:18: warning: implicit declaration of function ‘getopt’; did you mean ‘getsubopt’? [-Wimplicit-function-declaration]
  191 |     while (( i = getopt( ac, av, "daupf:c:t:s:h:" )) != EOF )
      |                  ^~~~~~
      |                  getsubopt
sph2pipe.c: In function ‘copySamples’:
sph2pipe.c:537:3: warning: implicit declaration of function ‘swab’ [-Wimplicit-function-declaration]
  537 |   swab( outbuf, inpbuf, nb );      /* it, do byte swapping too */
      |   ^~~~
200 OK
Length: unspecified [application/zip]
Saving to: ‘cub-1.8.0.zip’

cub-1.8.0.zip                                                  [ <=>                                                                                                                                  ] 588.28K  3.15MB/s    in 0.2s    

2021-05-06 21:13:47 (3.15 MB/s) - ‘cub-1.8.0.zip’ saved [602396]

unzip -oq cub-1.8.0.zip
rm -f cub
ln -s cub-1.8.0 cub
openfst-1.6.7.tar.gz                                       100%[=====================================================================================================================================>]   1.17M   770KB/s    in 1.6s    

2021-05-06 21:13:47 (770 KB/s) - ‘openfst-1.6.7.tar.gz’ saved [1230836/1230836]

tar xozf openfst-1.6.7.tar.gz

**Comment by Natalia-T** [comment]
Hi @charishnaidu,

If it was frozen at the last operation of your output (`tar xozf openfst-1.6.7.tar.gz`), probably your file system is too slow (for example, this can happen if you use a network file system (NFS)).

To check this, you could run `tar xozf openfst-1.6.7.tar.gz` directly from the command line (not from the installation script) in the same file system.

If it freezes again, you could try unzip on the system disc as follows:

```
mkdir /tmp/openfst
cp openfst-1.6.7.tar.gz /tmp/openfst
cd /tmp/openfst
tar xozf openfst-1.6.7.tar.gz 
```

**Comment by ghost** [comment]
Thanks Natalia... It worked and I am closing the ticket
