### ISSUE TITLE
Install.sh issue

### ISSUE THREAD

**Issue by Wujianting** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020#11]
Can you help me？
I got an error when I run install.sh after git clone.
I am very confused, because I just follow the original requirement.txt operation, I don’t know what went wrong.
The general problem is as follows:
![1](https://user-images.githubusercontent.com/33387466/129052257-e9551189-f126-4f00-b731-ba57b1fd5b2c.PNG)

**Comment by Natalia-T** [comment]
Hi @Wujianting,

Thank you for reporting the issue.

I replaced the latest version of miniconda (`Miniconda3-latest, python=3.9`) in install.sh with a fixed version (`Miniconda3-py38_4.10.3, python=3.8`).

Please check the last commit: https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020/commit/19eb8bc25a5ec6ec9aa485692cb93942c915d3d0

**Comment by Wujianting** [comment]
Hello, thanks for the reply, are you sure this is ok. After my try, I find that the fixed version (Miniconda3-py38_4.10.3, python=3.8) is still not feasible. But I found that the fixed version (Miniconda3-py37_4.10.3-Linux-x86_64.sh) and (Miniconda3-4.7.12.1-Linux-x86_64.sh) are Error-free

**Comment by Natalia-T** [comment]
I tested the last version of install.sh (with `Miniconda3-py38_4.10.3`) on several servers with differen OS versions (including `Ubuntu 16.04.7`, `18.04.5`, `20.04.2`). It worked in all cases (*for Ubuntu 20.04, a Kaldi update is needed).

**Comment by Wujianting** [comment]
Thank you for your help
