### ISSUE TITLE
 The stage9(stage a.4) problem of run.sh

### ISSUE THREAD

**Issue by ingosiegert** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020#14]
In Stage a.4: Make netcdf data for VC, I got an "ModuleNotFoundError":

`from ioTools import readwrite`
`ModuleNotFoundError: No module named 'ioTools'` 

I tested the related python script using python 3, installed the module but still get this error.

What does the function do, is there a replacement possible?

**Comment by Natalia-T** [comment]
Hi @ingosiegert,

It seems that by some reason, the following init.sh script has not completed properly:

https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020/blob/master/baseline/local/anon/make_netcdf.sh#:~:text=%23%20initialize%20pytools,am/init.sh

Could you please after line:

`. local/vc/am/init.sh`

check:

`echo $PYTHONPATH`

This module is related to the TTS part, I do not think it is possible to replace it easily.

**Comment by ingosiegert** [comment]
Hi @Natalia-T,

you are right, there is some misconfiguration in the python paths:
`:/pyTools:/$HOME/Voice-Privacy-Challenge-2020/baseline/local/vc/am`

I've seen that the ioTools are located under `./Voice-Privacy-Challenge-2020/nii/pyTools/ioTools`

Can I simply add this path, or is there a more general, or other paths to add?

**Comment by Natalia-T** [comment]
Hi @ingosiegert,

I think your installation (`install.sh`) has not been completed.

Could you please check the `.done*` files  and `env.sh` in your directory `$HOME/Voice-Privacy-Challenge-2020` ?

Please see the full list of the required `.done*` files and an example of a good `env.sh` in the following issue: https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020/issues/12#issuecomment-900765420
