### ISSUE TITLE
Install.sh Issue

### ISSUE THREAD

**Issue by AyaAlJafari** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020#4]
I'm trying to run the baseline. However, install.sh fails (my g++ version is set to 4.8.5)

This is the error I'm getting: 

/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
# --error 0x1 --
Makefile:32: recipe for target 'cu-kernels.o' faileda
make[1]: *** [cu-kernels.o] Error 1
make[1]: Leaving directory '/home/corpus/POCs/Voice-Privacy-Challenge-2020/kaldi/src/cudamatrix'
Makefile:136: recipe for target 'cudamatrix' failed
make: *** [cudamatrix] Error 2
ar -cr kaldi-hmm.a hmm-topology.o transition-model.o hmm-utils.o tree-accu.o posterior.o hmm-test-utils.o
ranlib kaldi-hmm.a
g++ -shared -o libkaldi-hmm.so -Wl,--no-undefined -Wl,--as-needed  -Wl,-soname=libkaldi-hmm.so,--whole-archive kaldi-hmm.a -Wl,--no-whole-archive  -Wl,-rpath=/home/corpus/POCs/Voice-Privacy-Challenge-2020/kaldi/tools/openfst-1.6.7/lib -rdynamic -Wl,-rpath=/home/corpus/POCs/Voice-Privacy-Challenge-2020/kaldi/src/lib  ../tree/libkaldi-tree.so  ../util/libkaldi-util.so  ../matrix/libkaldi-matrix.so  ../base/libkaldi-base.so /home/corpus/POCs/Voice-Privacy-Challenge-2020/kaldi/tools/openfst-1.6.7/lib/libfst.so -L/opt/intel/mkl/lib/intel64 -Wl,-rpath=/opt/intel/mkl/lib/intel64 -lmkl_intel_lp64  -lmkl_core  -lmkl_sequential    -ldl -lpthread -lm  -lm -lpthread -ldl
kaldi-hmm.a(hmm-utils.o): In function `fst::internal::FstImpl<fst::ReverseArc<fst::ArcTpl<fst::TropicalWeightTpl<float> > > >::WriteFstHeader(fst::Fst<fst::ReverseArc<fst::ArcTpl<fst::TropicalWeightTpl<float> > > > const&, std::ostream&, fst::FstWriteOptions const&, int, std::string const&, unsigned long, fst::FstHeader*)':
/home/corpus/POCs/Voice-Privacy-Challenge-2020/kaldi/tools/openfst-1.6.7/include/fst/fst.h:746: undefined reference to `fst::FstHeader::Write(std::ostream&, std::string const&) const'
kaldi-hmm.a(hmm-utils.o): In function `fst::internal::FstImpl<fst::ArcTpl<fst::TropicalWeightTpl<float> > >::WriteFstHeader(fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > > const&, std::ostream&, fst::FstWriteOptions const&, int, std::string const&, unsigned long, fst::FstHeader*)':
/home/corpus/POCs/Voice-Privacy-Challenge-2020/kaldi/tools/openfst-1.6.7/include/fst/fst.h:746: undefined reference to `fst::FstHeader::Write(std::ostream&, std::string const&) const'
collect2: error: ld returned 1 exit status
../makefiles/default_rules.mk:53: recipe for target 'libkaldi-hmm.so' failed
make[1]: *** [libkaldi-hmm.so] Error 1
make[1]: Leaving directory '/home/corpus/POCs/Voice-Privacy-Challenge-2020/kaldi/src/hmm'
Makefile:136: recipe for target 'hmm' failed
make: *** [hmm] Error 2

Can anyone tell me what am I missing?

**Comment by Natalia-T** [comment]
Hi @AyaAlJafari,

It seems that you have a problem in the Kaldi installation.
The Kaldi installation is called from the install.sh script:

```
git clone https://github.com/kaldi-asr/kaldi.git 
cd kaldi 
git reset --hard cbdbedefcdd47e02a685c1dc2d1b128c30bdf6b2
cd tools
make 
cd ../src
./configure --shared
make depend
make

```
You could try to do these steps independently to check if the problem is in your environment for the Kaldi installation.
