### ISSUE TITLE
Issue when running baseline/run.sh

### ISSUE THREAD

**Issue by reppy4620** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020#7]
Thank you for your great repository.
I'm trying to run baseline and I met following error.
```
~/Voice-Privacy-Challenge-2020$ ./install.sh
...
...  a lot of logs about installation
...
~/Voice-Privacy-Challenge-2020$ cd baseline
~/Voice-Privacy-Challenge-2020/baseline$ ./run.sh
path.sh: line 7: ../env.sh: No such file or directory
```
I couldn't find above script.

Please let me know if you have any solutions.
Thank you.

**Comment by Natalia-T** [comment]
Hi @reppy4620,

Could you please run install.sh from the "clean" version (after git clone) and attach the resulting log file?

./install.sh &> install.log

**Comment by reppy4620** [comment]
Thank you for your quick reply.
I noticed that env.sh have to be generated by install.sh.
In my case, install.sh generated '.done-venv' and '.done-kaldi-tools', and output following error.
I overlooked this.

```
Configuring MKL library directory: ***configure failed: MKL libraries could not be found. Please use the switch --mkl-libdir or try another math library, e.g. --mathlib=ATLAS (would be slower) ***
```

I'll redo installation procedure.

**Comment by reppy4620** [comment]
After installed MKL library, above issue has gone, but new error e.g. constraints of CUDA and gcc version for installing kaldi is appeared.
As it's unrelated this repo, I close this issue.
