### ISSUE TITLE
python kills the scoring ...gives memory error

### ISSUE THREAD

**Issue by Gauri-Prajapati** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020#8]
I am working on GPU with 64-bit python. Still, when I run the code for finding similarity scores (at 'scores_calibration.py' output files are not generated), particularly for vctk_trials this error occurs. Please let me know how can I do? I am attaching the error image.

![IMG_20201017_115624](https://user-images.githubusercontent.com/68062154/96371538-c810e000-117f-11eb-92bf-9ac11fec02ed.jpg)

**Comment by Natalia-T** [comment]
Hi @Gauri-Prajapati,

Could you please precise what is the size of RAM on your machine?

**Comment by Gauri-Prajapati** [comment]
RAM :  31.4 GiB

**Comment by Gauri-Prajapati** [comment]
sorry but,
CPU RAM : 31.4 GiB
GPU RAM : 12 GB
(ignore the previous message)
Thanks

**Comment by Natalia-T** [comment]
Thank you @Gauri-Prajapati for this information.

For Stage 15, the required memory size was ~30GB (CPU RAM). 

Please check the last commit: https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2020/commit/1dcdcdae620fe2def0f35a203b598c42a5c8df1d

I removed some parallel computations in compute_similarity_matrices_metrics.sh, and now ~12GB should be sufficient.

**Comment by Gauri-Prajapati** [comment]
Now it's working. Thanks.
